#!/bin/bash

[ "$1" != "start" ] && [ "$1" != "restart" ] && exit 0

if [ "$1" == "start" ]; then
	
    ipset create unblock hash:net # Создание IP таблицы
	
#################################################################################################
### Формирование дополнительного конфигурационного файла из заданного списка доменов
	
	cat /dev/null > /etc/unblock.dnsmasq

    while read line || [ -n "$line" ]; do

        [ -z "$line" ] && continue
        [ "${line:0:1}" = "#" ] && continue
		
		echo $line | grep -Eq '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' && continue
		
		echo "ipset=/$line/unblock" >> /etc/unblock.dnsmasq
		
	done < /etc/unblock.txt
	
    /etc/init.d/dnsmasq restart #	Перезапуск DNS - сервера
	
#################################################################################################
### Заполнение таблицы IP-адресами заданного списка доменов
	
    until ADDRS=$(dig +short google.com @localhost) && [ -n "$ADDRS" ] > /dev/null 2>&1; do sleep 5; done

    while read line || [ -n "$line" ]; do

        [ -z "$line" ] && continue
        [ "${line:0:1}" = "#" ] && continue

        cidr=$(echo $line | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]{1,2}')

        if [ ! -z "$cidr" ]; then
            ipset -exist add unblock $cidr
            continue
        fi
  
        range=$(echo $line | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}-[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')

        if [ ! -z "$range" ]; then
            ipset -exist add unblock $range
            continue
        fi
  
        addr=$(echo $line | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')

        if [ ! -z "$addr" ]; then
            ipset -exist add unblock $addr
            continue
        fi

        dig +short $line @localhost | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | awk '{system("ipset -exist add unblock "$1)}'

    done < /etc/unblock.txt
	
	exit 0
fi

if [ "$1" == "restart" ]; then

    ipset flush unblock # Очистка IP таблицы

#################################################################################################
### Формирование дополнительного конфигурационного файла из заданного списка доменов
	
	cat /dev/null > /etc/unblock.dnsmasq

    while read line || [ -n "$line" ]; do

        [ -z "$line" ] && continue
        [ "${line:0:1}" = "#" ] && continue
		
		echo $line | grep -Eq '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' && continue
		
		echo "ipset=/$line/unblock" >> /etc/unblock.dnsmasq
		
	done < /etc/unblock.txt

    /etc/init.d/dnsmasq restart # Перезапуск DNS - сервера

#################################################################################################
### Заполнение таблицы IP-адресами заданного списка доменов
	
    until ADDRS=$(dig +short google.com @localhost) && [ -n "$ADDRS" ] > /dev/null 2>&1; do sleep 5; done

    while read line || [ -n "$line" ]; do

        [ -z "$line" ] && continue
        [ "${line:0:1}" = "#" ] && continue

        cidr=$(echo $line | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]{1,2}')

        if [ ! -z "$cidr" ]; then
            ipset -exist add unblock $cidr
            continue
        fi
  
        range=$(echo $line | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}-[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')

        if [ ! -z "$range" ]; then
            ipset -exist add unblock $range
            continue
        fi
  
        addr=$(echo $line | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')

        if [ ! -z "$addr" ]; then
            ipset -exist add unblock $addr
            continue
        fi

        dig +short $line @localhost | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | awk '{system("ipset -exist add unblock "$1)}'

    done < /etc/unblock.txt

    exit 0
fi